FROM ruby:3.1.3

ARG FUNCTION_DIR="/function"

# Install bundler
RUN gem install bundler

# Install the Runtime Interface Client
RUN gem install aws_lambda_ric

# Copy function code
RUN mkdir -p ${FUNCTION_DIR}
COPY app.rb ${FUNCTION_DIR}

WORKDIR ${FUNCTION_DIR}

ENTRYPOINT ["/usr/local/bundle/bin/aws_lambda_ric"]
CMD ["app.LambdaFunction::Handler.process"]
