FROM quay.io/keycloak/keycloak:14.0.0

ENV KEYCLOAK_USER=admin \
  KEYCLOAK_PASSWORD=admin \
  DB_VENDOR=POSTGRES \
  DB_ADDR=arjuna.db.elephantsql.com \
  DB_DATABASE=izrzioiw \
  DB_USER=izrzioiw \
  DB_PASSWORD=RRVq7alBRjwWgIJp1l2BbvR6O7DFrckx
